version: '1.0'


services:

  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: nginx
    environment:
      - SERVER_NAME=0.0.0.0
    restart: always
    network_mode: host

  
  dbsql:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      - MYSQL_DATABASE=${APOLLO_MYSQL_DATABASE}
      - MYSQL_USER=${APOLLO_MYSQL_USER}
      - MYSQL_PASSWORD=${APOLLO_MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${APOLLO_MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./creds/sample-mysql.sql:/docker-entrypoint-initdb.d/init-users.sql


  dbmongo:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${APOLLO_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${APOLLO_MONGO_PASSWORD}
    ports:
      - 27017:27017


  backend:
    build: .
    image: apollo:latest
    container_name: apollo
    command: python Apollo/manage.py runserver 0.0.0.0:8000 &
    # command: tail -f /dev/null # runs server indifinitely
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=Apollo.settings
      - DB_NAME=${APOLLO_MYSQL_DATABASE}
      - DB_USER=${APOLLO_MYSQL_USER}
      - DB_PASSWORD=${APOLLO_MYSQL_PASSWORD}
      - DB_HOST=dbsql
      - MONGODB_CONNECTION_STRING=mongodb://${APOLLO_MONGO_USER}:${APOLLO_MONGO_PASSWORD}@dbmongo:27017
      - MARIADB_CONFIG=/usr/bin/mariadb_config
    depends_on:
      - dbsql
      - dbmongo


volumes:
  mariadb_data:
