###
POST http://localhost:8000/speech
Content-Type: application/json

{ "prompt": "No, what all information do you know about my heart already?" }


### test route
POST http://localhost:8000/test
Authorization: gAAAAABmequXkED0aAVd9ARpaC4OL4Gm_9fjcwc3VeAHUD5cjMmqQCHEZtelLhsBIusYRE0HLX4tSTJQr_AzFM7KhZAr_bMi0-wPdr__Ln4js8BS6QtLwWUrETd1Lax9qo1H3Rrz20fQ9UxJn2QLtEscCd1J4AagcgUYBYq0GRMj9iYeYhmybZl7SIP6BfU1-Bi6FL0K9tE6cA309gSdYYrhJUDI5WeBC1WXQ3PCJF6UEzH_Ivz5k2BPlavd7-KERZhWYfAZ6jOFRju5_DHNfQKjCVl0VkizgA==


### goal route
GET http://localhost:8000/goal
Authorization: gAAAAABmequXkED0aAVd9ARpaC4OL4Gm_9fjcwc3VeAHUD5cjMmqQCHEZtelLhsBIusYRE0HLX4tSTJQr_AzFM7KhZAr_bMi0-wPdr__Ln4js8BS6QtLwWUrETd1Lax9qo1H3Rrz20fQ9UxJn2QLtEscCd1J4AagcgUYBYq0GRMj9iYeYhmybZl7SIP6BfU1-Bi6FL0K9tE6cA309gSdYYrhJUDI5WeBC1WXQ3PCJF6UEzH_Ivz5k2BPlavd7-KERZhWYfAZ6jOFRju5_DHNfQKjCVl0VkizgA==



