

POST http://127.0.0.1:8000/user/register/
Content-Type: application/json

{}


### user details
GET http://127.0.0.1:8000/user/details/
Authorization: Bearer gAAAAABmfFyeuOLKEZwco9gfatXy80oaK9rSL5irfzrF4HzkJNPCSZVjWD7Q9UCpXnzpfkldScpDE5DNxhbxMHnb_K3XwiSBjeIFyHsv9_O90Cf_TgjjcdcST_tnMFqjKApPgjk03XIRdbGUYwIIcK9MZT88WW7LOUaqYwUyv1N7xftBVV9EhLGHYlpYW9F1L-369rBYOiAFGXvr1t6LValvMzzM3rWWXiUztyFMFKYFm3J3WNmjeUOiRd6ahfzVVbfMCwl7iqF12n2rRZcEv46vWdNzDKppLg==


### Admin User Dashboard
GET http://127.0.0.1:8000/user/admin-users/?user__username=atharvanayak16@gmail.com
Authorization: Bearer gAAAAABmfFyeuOLKEZwco9gfatXy80oaK9rSL5irfzrF4HzkJNPCSZVjWD7Q9UCpXnzpfkldScpDE5DNxhbxMHnb_K3XwiSBjeIFyHsv9_O90Cf_TgjjcdcST_tnMFqjKApPgjk03XIRdbGUYwIIcK9MZT88WW7LOUaqYwUyv1N7xftBVV9EhLGHYlpYW9F1L-369rBYOiAFGXvr1t6LValvMzzM3rWWXiUztyFMFKYFm3J3WNmjeUOiRd6ahfzVVbfMCwl7iqF12n2rRZcEv46vWdNzDKppLg==


### Admin User Groups
GET http://127.0.0.1:8000/user/admin-groups/
Authorization: Bearer gAAAAABmfFyeuOLKEZwco9gfatXy80oaK9rSL5irfzrF4HzkJNPCSZVjWD7Q9UCpXnzpfkldScpDE5DNxhbxMHnb_K3XwiSBjeIFyHsv9_O90Cf_TgjjcdcST_tnMFqjKApPgjk03XIRdbGUYwIIcK9MZT88WW7LOUaqYwUyv1N7xftBVV9EhLGHYlpYW9F1L-369rBYOiAFGXvr1t6LValvMzzM3rWWXiUztyFMFKYFm3J3WNmjeUOiRd6ahfzVVbfMCwl7iqF12n2rRZcEv46vWdNzDKppLg==


### Admin User Groups manager
POST http://127.0.0.1:8000/user/admin-groups-manager/
# DELETE http://127.0.0.1:8000/user/admin-groups-manager/
Authorization: Bearer gAAAAABmfFyeuOLKEZwco9gfatXy80oaK9rSL5irfzrF4HzkJNPCSZVjWD7Q9UCpXnzpfkldScpDE5DNxhbxMHnb_K3XwiSBjeIFyHsv9_O90Cf_TgjjcdcST_tnMFqjKApPgjk03XIRdbGUYwIIcK9MZT88WW7LOUaqYwUyv1N7xftBVV9EhLGHYlpYW9F1L-369rBYOiAFGXvr1t6LValvMzzM3rWWXiUztyFMFKYFm3J3WNmjeUOiRd6ahfzVVbfMCwl7iqF12n2rRZcEv46vWdNzDKppLg==
Content-Type: application/json

{
    "name": "Testing"
}


### UserGroup Manager
POST http://127.0.0.1:8000/user/admin-user-groups-manager/
Authorization: Bearer gAAAAABmfFyeuOLKEZwco9gfatXy80oaK9rSL5irfzrF4HzkJNPCSZVjWD7Q9UCpXnzpfkldScpDE5DNxhbxMHnb_K3XwiSBjeIFyHsv9_O90Cf_TgjjcdcST_tnMFqjKApPgjk03XIRdbGUYwIIcK9MZT88WW7LOUaqYwUyv1N7xftBVV9EhLGHYlpYW9F1L-369rBYOiAFGXvr1t6LValvMzzM3rWWXiUztyFMFKYFm3J3WNmjeUOiRd6ahfzVVbfMCwl7iqF12n2rRZcEv46vWdNzDKppLg==
Content-Type: application/json

{
    "user_id": 10,
    "group_ids": [2]
}



