# Generated by Django 4.1 on 2024-05-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserManager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="email_secret",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="password_change_secret",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
