# Generated by Django 4.1 on 2024-08-26 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Google',
            fields=[
                ('user_details', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='UserManager.userdetails')),
                ('google_id', models.CharField(max_length=55, null=True)),
                ('refresh_token', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'user_account_google',
            },
        ),
        migrations.CreateModel(
            name='LoginType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('api_version', models.CharField(max_length=10, unique=True)),
                ('archived', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'login_type',
            },
        ),
        migrations.AddField(
            model_name='userdetails',
            name='email_secret_generated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='last_password_change_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='email_secret',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='password_change_secret',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='login_type',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UserManager.logintype'),
        ),
    ]
