# Generated by Django 4.1 on 2024-05-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserManager", "0002_alter_userdetails_email_secret_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="email_secret_generated_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
