# Generated by Django 4.1 on 2024-05-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserManager", "0003_userdetails_email_secret_generated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="last_password_change_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
