# Generated by Django 5.1.1 on 2024-09-09 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0002_google_logintype_and_more'),
        ('UserManager', '0004_userdetails_last_password_change_at'),
    ]

    operations = [
    ]
